### ISSUE TITLE
Hello team, as part of the Legal Analytics lab we are working on a package called "fuzzywuzzy" which is not installed in Python2.x. Could you please install the same? Thanks

### ISSUE THREAD

**Issue by sruthipisipati** [institute4insight/institute4insight.github.io#2]
THIS POST IS PUBLIC!
DO NOT INCLUDE ANY PERSONAL OR SENSITIVE INFORMATION!
DO NOT INCLUDE PASSWORDS OR EMAIL ADDRESSES!

**Is your installation or upgrade request related to a project? Please describe.**
A clear and concise description of the project.

**Describe features and functionality of the requested package or upgrade.**
A clear and concise description of the provided features, and benefits.

**Describe alternatives you've considered**

**Additional context**

**Comment by kingmolnar** [comment]
The package 'fuzzywuzzy' has been installed for Python 2.7 and 3.4
