### ISSUE TITLE
Not able to display charts in Jupyter notebook

### ISSUE THREAD

**Issue by attsbin** [institute4insight/institute4insight.github.io#3]
**System**
Include the hostname of the affected system.
 
Not able to display charts in Jupyter Notebook. 

**To Reproduce**
import matplotlib.pyplot as plt
plt.hist(ml_df.rating)

**Expected behavior**
Display histogram 

**Terminal output**
TclError: no display name and no $DISPLAY environment variable

**Additional context**
not able to display any charts , have tried using multiple libraries. Every visualization library gives the same error.

**Comment by kingmolnar** [comment]
You need to include the line 
%matplotlib inline
in your code before plotting.

The following does the trick:
%matplotlib inline
import matplotlib.pyplot as plt
 
See: https://nbviewer.jupyter.org/github/ipython/ipython/blob/1.x/examples/notebooks/Part%203%20-%20Plotting%20with%20Matplotlib.ipynb <https://nbviewer.jupyter.org/github/ipython/ipython/blob/1.x/examples/notebooks/Part%203%20-%20Plotting%20with%20Matplotlib.ipynb> 


Peter Molnar
peter@kingmolnar.com

**Comment by kingmolnar** [comment]
``
