### ISSUE TITLE
Request to install mysql.connector library on the cluster

### ISSUE THREAD

**Issue by solozyf** [institute4insight/institute4insight.github.io#4]
THIS POST IS PUBLIC!
DO NOT INCLUDE ANY PERSONAL OR SENSITIVE INFORMATION!
DO NOT INCLUDE PASSWORDS OR EMAIL ADDRESSES!

**Is your installation or upgrade request related to a project? Please describe.**
Yes, it's about our research project with Prof. Javad

**Describe features and functionality of the requested package or upgrade.**
It could help us to connect with the mysql database to access data for further analysis

**Describe alternatives you've considered**
We tried to run the python code at our own laptops, however, it is quite slow and therefore we need ato run it on the cluster. 

**Additional context**

**Comment by kingmolnar** [comment]
Where is the MySQL database located? Connecting to a SQL server won’t make your program run any faster than on the laptop.

Have you considered using Spark for your analysis task?

**Comment by kingmolnar** [comment]
Please, provide the requested information. Otherwise, I will close the ticket.
Thanks

**Comment by solozyf** [comment]
Hello Professor Peter, 
Sorry for the late reply. The MySQL database is located in the GSU server. The professor from the GSU CS department is responsible for storing the data.  We haven't explored Spark yet. Would you mind providing more information regarding the Spark? Thanks.

**Comment by kingmolnar** [comment]
The packages mysql and mysqlclient https://pypi.org/project/mysqlclient/ have been installed for Python 2.7 and 3.6

The easiest way to connect to the SQL server is via SqlAlchemy
https://docs.sqlalchemy.org/en/latest/dialects/mysql.html#module-sqlalchemy.dialects.mysql.mysqldb
