### ISSUE TITLE
Request to install pdf2image module on the cluster

### ISSUE THREAD

**Issue by ywoo3** [institute4insight/institute4insight.github.io#5]
THIS POST IS PUBLIC!
DO NOT INCLUDE ANY PERSONAL OR SENSITIVE INFORMATION!
DO NOT INCLUDE PASSWORDS OR EMAIL ADDRESSES!

**Is your installation or upgrade request related to a project? Please describe.**
We are currently working for the GRA Bloomberg Analytics project.

**Describe features and functionality of the requested package or upgrade.**
pdf2image is necessary. Converts pdfs to images. poppler-utils is required before installing the pdf2image module.

**Describe alternatives you've considered**

**Additional context**

**Comment by kingmolnar** [comment]
Installed for Python 2.7 and 3.6
